# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI Build

concurrency:
  group: CI-build
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build with DGMJR-IO SDK
      uses: dgmjr-actions/build-using-dgmjrsdk@main
      with: 
        git-token: ${{ secrets.GITHUB_TOKEN }}
        repo: dgmjr-io/Abstractions
        project-file-path: Dgmjr.Abstractions.csproj
        push-github: true
